services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    command: redis-server --requirepass password

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        MIX_ENV: dev
    container_name: chessquo
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      PORT: 3000
      SECRET_KEY_BASE: 0NXXoVvovCGUtL/B1ox/RRckWD/pJq5L5LdZAmcKRYE9fBctitwDbv2IZGArMaEX
      PHX_HOST: localhost
    restart: always
